### ISSUE TITLE
App and subapp rename

### ISSUE THREAD

**Issue by ilkemerol** [gurkanakdeniz/kicket#34]
- [x] - execode --> kicket
- [x] - execode-java --> kicket-java
- [x] - execode-py --> kicket-py
- [x] - execode-node --> kicket-node
- [x] - execode-html --> kicket-html
- [x] - execode-php --> kicket-php

**Comment by gurkanakdeniz** [comment]
- [x] - execode --> kicket
- [x] - execode-java --> kicket-java
- [x] - execode-py --> kicket-py
- [x] - execode-node --> kicket-node
- [x] - execode-html --> kicket-html
- [x] - execode-php --> kicket-php
